// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingSystem.Infrastructure.Persistence;

#nullable disable

namespace TicketingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428021245_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketingSystem.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            EventDate = new DateTimeOffset(new DateTime(2026, 6, 15, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Concierto de Rock",
                            Status = "Active",
                            Venue = "Estadio Luna Park"
                        });
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ReservedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SeatId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowIdentifier")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Available");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Seats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000001"),
                            RowIdentifier = "A",
                            SeatNumber = 1,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000002"),
                            RowIdentifier = "A",
                            SeatNumber = 2,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000003"),
                            RowIdentifier = "A",
                            SeatNumber = 3,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000004"),
                            RowIdentifier = "A",
                            SeatNumber = 4,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000005"),
                            RowIdentifier = "A",
                            SeatNumber = 5,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000006"),
                            RowIdentifier = "A",
                            SeatNumber = 6,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000007"),
                            RowIdentifier = "B",
                            SeatNumber = 1,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000008"),
                            RowIdentifier = "B",
                            SeatNumber = 2,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000009"),
                            RowIdentifier = "B",
                            SeatNumber = 3,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000010"),
                            RowIdentifier = "B",
                            SeatNumber = 4,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000011"),
                            RowIdentifier = "B",
                            SeatNumber = 5,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000012"),
                            RowIdentifier = "B",
                            SeatNumber = 6,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000013"),
                            RowIdentifier = "B",
                            SeatNumber = 7,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000014"),
                            RowIdentifier = "B",
                            SeatNumber = 8,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000015"),
                            RowIdentifier = "C",
                            SeatNumber = 1,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000016"),
                            RowIdentifier = "C",
                            SeatNumber = 2,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000017"),
                            RowIdentifier = "C",
                            SeatNumber = 3,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000018"),
                            RowIdentifier = "C",
                            SeatNumber = 4,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000019"),
                            RowIdentifier = "C",
                            SeatNumber = 5,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000020"),
                            RowIdentifier = "C",
                            SeatNumber = 6,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000021"),
                            RowIdentifier = "C",
                            SeatNumber = 7,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000022"),
                            RowIdentifier = "C",
                            SeatNumber = 8,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000023"),
                            RowIdentifier = "C",
                            SeatNumber = 9,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("bb000000-0000-0000-0000-000000000024"),
                            RowIdentifier = "C",
                            SeatNumber = 10,
                            SectorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000001"),
                            RowIdentifier = "D",
                            SeatNumber = 1,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000002"),
                            RowIdentifier = "D",
                            SeatNumber = 2,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000003"),
                            RowIdentifier = "D",
                            SeatNumber = 3,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000004"),
                            RowIdentifier = "D",
                            SeatNumber = 4,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000005"),
                            RowIdentifier = "D",
                            SeatNumber = 5,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000006"),
                            RowIdentifier = "D",
                            SeatNumber = 6,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000007"),
                            RowIdentifier = "D",
                            SeatNumber = 7,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000008"),
                            RowIdentifier = "D",
                            SeatNumber = 8,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000009"),
                            RowIdentifier = "E",
                            SeatNumber = 1,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000010"),
                            RowIdentifier = "E",
                            SeatNumber = 2,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000011"),
                            RowIdentifier = "E",
                            SeatNumber = 3,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000012"),
                            RowIdentifier = "E",
                            SeatNumber = 4,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000013"),
                            RowIdentifier = "E",
                            SeatNumber = 5,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000014"),
                            RowIdentifier = "E",
                            SeatNumber = 6,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000015"),
                            RowIdentifier = "E",
                            SeatNumber = 7,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000016"),
                            RowIdentifier = "E",
                            SeatNumber = 8,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000017"),
                            RowIdentifier = "E",
                            SeatNumber = 9,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000018"),
                            RowIdentifier = "E",
                            SeatNumber = 10,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000019"),
                            RowIdentifier = "F",
                            SeatNumber = 1,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000020"),
                            RowIdentifier = "F",
                            SeatNumber = 2,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000021"),
                            RowIdentifier = "F",
                            SeatNumber = 3,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000022"),
                            RowIdentifier = "F",
                            SeatNumber = 4,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000023"),
                            RowIdentifier = "F",
                            SeatNumber = 5,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000024"),
                            RowIdentifier = "F",
                            SeatNumber = 6,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000025"),
                            RowIdentifier = "F",
                            SeatNumber = 7,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000026"),
                            RowIdentifier = "F",
                            SeatNumber = 8,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000027"),
                            RowIdentifier = "F",
                            SeatNumber = 9,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000028"),
                            RowIdentifier = "F",
                            SeatNumber = 10,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000029"),
                            RowIdentifier = "F",
                            SeatNumber = 11,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000030"),
                            RowIdentifier = "F",
                            SeatNumber = 12,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000031"),
                            RowIdentifier = "G",
                            SeatNumber = 1,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000032"),
                            RowIdentifier = "G",
                            SeatNumber = 2,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000033"),
                            RowIdentifier = "G",
                            SeatNumber = 3,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000034"),
                            RowIdentifier = "G",
                            SeatNumber = 4,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000035"),
                            RowIdentifier = "G",
                            SeatNumber = 5,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000036"),
                            RowIdentifier = "G",
                            SeatNumber = 6,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000037"),
                            RowIdentifier = "G",
                            SeatNumber = 7,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000038"),
                            RowIdentifier = "G",
                            SeatNumber = 8,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000039"),
                            RowIdentifier = "G",
                            SeatNumber = 9,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000040"),
                            RowIdentifier = "G",
                            SeatNumber = 10,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000041"),
                            RowIdentifier = "G",
                            SeatNumber = 11,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000042"),
                            RowIdentifier = "G",
                            SeatNumber = 12,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000043"),
                            RowIdentifier = "G",
                            SeatNumber = 13,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000044"),
                            RowIdentifier = "G",
                            SeatNumber = 14,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000045"),
                            RowIdentifier = "H",
                            SeatNumber = 1,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000046"),
                            RowIdentifier = "H",
                            SeatNumber = 2,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000047"),
                            RowIdentifier = "H",
                            SeatNumber = 3,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000048"),
                            RowIdentifier = "H",
                            SeatNumber = 4,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000049"),
                            RowIdentifier = "H",
                            SeatNumber = 5,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000050"),
                            RowIdentifier = "H",
                            SeatNumber = 6,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000051"),
                            RowIdentifier = "H",
                            SeatNumber = 7,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000052"),
                            RowIdentifier = "H",
                            SeatNumber = 8,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000053"),
                            RowIdentifier = "H",
                            SeatNumber = 9,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000054"),
                            RowIdentifier = "H",
                            SeatNumber = 10,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000055"),
                            RowIdentifier = "H",
                            SeatNumber = 11,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000056"),
                            RowIdentifier = "H",
                            SeatNumber = 12,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000057"),
                            RowIdentifier = "H",
                            SeatNumber = 13,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000058"),
                            RowIdentifier = "H",
                            SeatNumber = 14,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000059"),
                            RowIdentifier = "H",
                            SeatNumber = 15,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000060"),
                            RowIdentifier = "H",
                            SeatNumber = 16,
                            SectorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Available",
                            Version = 0
                        });
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Sectors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Capacity = 60,
                            EventId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "General",
                            Price = 80000m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Capacity = 24,
                            EventId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "VIP",
                            Price = 110000m
                        });
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Email = "test@ticketing.com",
                            Name = "Usuario Test",
                            PasswordHash = "hash_simulado"
                        });
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("TicketingSystem.Domain.Entities.Seat", "Seat")
                        .WithOne("ActiveReservation")
                        .HasForeignKey("TicketingSystem.Domain.Entities.Reservation", "SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketingSystem.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Seat", b =>
                {
                    b.HasOne("TicketingSystem.Domain.Entities.Sector", "Sector")
                        .WithMany("Seats")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Sector", b =>
                {
                    b.HasOne("TicketingSystem.Domain.Entities.Event", "Event")
                        .WithMany("Sectors")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Event", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Seat", b =>
                {
                    b.Navigation("ActiveReservation");
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TicketingSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
